services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
    container_name: weather-frontend
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped